In [1]:
import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt

import tensorflow as tf

import gpflow
from gpflow.utilities import read_values, multiple_assign, set_trainable
from gpflow.inducing_variables import InducingPoints
import gpmaniflow
from gpmaniflow.models.SVGP import SVGP

import gpmaniflow.samplers
from gpmaniflow.samplers import initialize_sampler
from gpmaniflow.curves import BezierCurve

In [12]:
end_points = np.array([[[0,0]],[[1,1]]])
end_points.shape

c = BezierCurve(end_points, order = 2)
t = np.linspace(0,1, 10)
#print(t)
C = c(t)
#print(C)
C.shape


TensorShape([10, 2])

In [13]:
end_points.shape

(2, 1, 2)

In [4]:
dC = c.deriv(t)
dC

1
tf.Tensor(
[[0.5 0.5]
 [0.5 0.5]], shape=(2, 2), dtype=float64)
tf.Tensor([1. 1.], shape=(2,), dtype=float64)


<tf.Tensor: shape=(10, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])>

In [5]:
arc_length = tf.reduce_mean(tf.norm(dC, axis = 1))
arc_length

<tf.Tensor: shape=(), dtype=float64, numpy=1.4142135623730951>