In [2]:
import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt

import tensorflow as tf

import gpflow
from gpflow.utilities import read_values, multiple_assign, set_trainable
from gpflow.inducing_variables import InducingPoints
import gpmaniflow
from gpmaniflow.models.SVGP import SVGP

import gpmaniflow.samplers
from gpmaniflow.samplers import initialize_sampler
from gpmaniflow.curves import BezierCurve

In [3]:
end_points = np.array([[[0,0]],[[1,1]]])
end_points.shape

c = BezierCurve(end_points, order = 1)
t = np.linspace(0,1, 10)
print(t)
C = c(t)
print(C)
C.shape

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
tf.Tensor(
[[0.         0.        ]
 [0.11111111 0.11111111]
 [0.22222222 0.22222222]
 [0.33333333 0.33333333]
 [0.44444444 0.44444444]
 [0.55555556 0.55555556]
 [0.66666667 0.66666667]
 [0.77777778 0.77777778]
 [0.88888889 0.88888889]
 [1.         1.        ]], shape=(10, 2), dtype=float64)


TensorShape([10, 2])

In [4]:
c.control_points

<tf.Variable 'Variable:0' shape=(0, 1, 2) dtype=float64, numpy=array([], shape=(0, 1, 2), dtype=float64)>

In [5]:
dC = c.deriv(t)
dC

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float64)
tf.Tensor([1.], shape=(1,), dtype=float64)


<tf.Tensor: shape=(10, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])>

In [6]:
arc_length = tf.reduce_mean(tf.norm(dC, axis = 1))
arc_length

<tf.Tensor: shape=(), dtype=float64, numpy=1.4142135623730951>